### ISSUE TITLE
AS5600 Magnetic Encoder

### ISSUE THREAD

**Issue by joeyda** [ranenbg/Arduino-FFB-wheel#64] opened 2024-09-02 03:51 UTC
Hi, I have a brushless motor with an AS5600 magnetic encoder and an arduino pro micro, is it possible to work with your firmware using i2c?

**Comment by ranenbg** [comment] 2024-09-02 04:35
Hi, at the moment AS5600 is not supported in my firmware. I have no plans to implement its support in my firmware, as this type of encoders is not suitable for the ffb wheel due to not good enough response, speed, resolution and noise level. It is used mostly for digitizing pots, knobs or basic angle readout.

**Comment by joeyda** [comment] 2024-09-02 10:34
Good to know, thank you!On Sep 2, 2024, at 12:36 AM, Miloš Ranković ***@***.***> wrote:﻿
Hi, at the moment AS5600 is not supported in my firmware. I have no plans to implement its support in my firmware, as this type of encoders is not suitable for the ffb wheel due to not good enough response, speed, resolution and noise level. It is used mostly for digitizing pots, knobs or basic angle readout.

**Comment by joeyda** [comment] 2024-09-04 02:21
Thank you for the additional info. I was looking into making a small handheld wheel with a brushless gimbal motor since they are so quiet and tiny. I have a motor driver and was going to use simple FOC to control it

**Comment by ranenbg** [comment] 2024-09-09 08:47
Yes, I see why you want AS5600 in the controller like this it is more convenient due to the small space, but I still think an optical encoder is far superior. It will have higher resolution, no noise at all, and instant reaction speed plus you can easily add some gears to it, add a DC motor and a small h-bridge like LN298 and you're good to go.

**Comment by jairov96** [comment] 2024-09-10 17:06
That's dope, thank you very much!

Anywhere I can donate/buy a coffee to the cause?

**Comment by ranenbg** [comment] 2024-09-10 18:40
You're welcome. I still have to do some testing, but if you wish to donate there is my paypal in the GUI near bottom part of window.

**Comment by ranenbg** [comment] 2024-11-06 04:18
I'm closing this one, as I have already released firmware v240w firmware which supports AS5600 magnetic encoder via i2C bus.

**Closed by ranenbg** 2024-11-06 04:18 UTC
